version: "3"
services:
    redis:
        image: redis:alpine
    auth:
        container_name: auth
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        links:
            - redis
        depends_on:
            - redis
        environment:
            - SERVICE
            - API_KEY
            - PGCS
            - REDISCS
            - REFRESH_TOKEN_EXPIRES
            - JWT_SECRET
            - JWT_TOKEN_EXPIRES
            - BOT_TOKEN
            - MAILGUN_API_KEY
            - MAILGUN_DOMAIN
