name: CD

on:
    push:
        branches: [master, dev]

jobs:
    build:
        name: Build, push, and deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  fetch-depth: 0
            - run: |
                  git fetch origin master

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: NPM Install
              run: npm install

            - name: List services
              id: services
              run: echo ::set-output list=::$(node ./node_modules/@nrwl/cli/bin/nx.js affected:apps --plain --all  )
            
            - name: Echo services
              run: echo ${{ steps.services.outputs.list }}
            ## - name: Try script
            #   run: ./deployments/script.sh
